export const destinationDetailsStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    marginX: "64px",
    marginTop: "126px",
    marginBottom: "64px",
    gap: "48px",
  },
  topContentWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "32px",
  },
  headingContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  heading: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "40px",
    color: "#202445",
  },
  destinationDetails: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "54px",
  },
  detailRow: {
    display: "flex",
    flexDirection: "row",
    gap: "8px",
    alignItems: "center",
  },
  text: {
    color: "#797C9A",
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: 400,
  },
  icon: {
    color: "#797C9A",
    padding: "3px",
    backgroundColor: "#F5F5F5",
    borderRadius: "50%",
  },
  descriptionContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    alignItems: "center",
  },
  description: {
    color: "#404040",
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: 400,
    textAlign: "center",
  },
  featuresContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "26px",
  },
  features: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  schedule: {
    display: "flex",
    flexDirection: "column",
    gap: "32px",
  },
  buttonContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  scheduleGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "32px",
  },
};
