export const myToursStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    marginX: "64px",
    marginTop: "126px",
    marginBottom: "64px",
    gap: "32px",
  },
  headingWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  heading: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "40px",
    color: "#202445",
  },
  cardsWrapper: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "54px",
  },
  modal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "24px 32px",
    gap: "32px",
    display: "flex",
    flexDirection: "column",
  },
  modalTitle: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "20px",
    color: "#F83030",
  },
  modalDescription: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    color: "#404040",
  },
  modalTextWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  buttomsWrapper: {
    display: "flex",
    flexDirection: "row",
    gap: "10px",
    justifyContent: "flex-end",
  },
  cancelButton: {
    color: "#999",
    backgroundColor: "transparent",
    border: "1px solid #999",
    fontWeight: 500,
    paddingX: "24px",
    "&:hover": {
      backgroundColor: "#999",
      color: "#fff",
    },
  },
  deleteButton: {
    color: "#fff",
    backgroundColor: "#F83030",
    paddingX: "24px",
    fontWeight: 500,
    "&:hover": {
      color: "#F83030",
      background: "#fff",
      outline: "1px solid #F83030",
    },
  },
};
