export const homeStyles = {
  container: {
    position: "relative",
    backgroundImage: 'url("../../src/assets/Images/mainBg.png")',
    backgroundPosition: "right",
    backgroundRepeat: "no-repeat",
    height: "100vh",
    zIndex: 10,
    display: "flex",
    flexDirection: "row",
    marginLeft: "64px",
    backgroundSize: "contain",
  },
  leftContentWrapper: {
    display: "flex",
    flexDirection: "column",
    marginTop: "187px",
    flex: 1,
    gap: "40px",
  },
  textWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  heading: {
    fontFamily: "Poppins",
    fontWeight: 600,
    color: "#202445",
    fontSize: 64,
    lineHeight: "normal",
  },
  headingFirstWord: {
    display: "inline",
    position: "relative",
    "&::before": {
      content: "''",
      position: "absolute",
      bottom: "-20px",
      left: 0,
      width: "100%",
      height: "40px",
      backgroundImage: 'url("../../src/assets/Images/lineBelow.svg")',
      backgroundRepeat: "no-repeat",
      backgroundSize: "contain",
      zIndex: -1,
    },
  },
  secondaryText: {
    fontFamily: "Poppins",
    fontSize: "24px",
    fontWeight: 400,
    width: "75%",
  },
  button: {
    width: "fit-content",
  },
  imageWrapper: {
    display: "flex",
    flex: 1,
    position: "relative",
  },
  gridContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    marginRight: "18px",
    display: "grid",
    gridTemplateColumns: "330px 330px",
    gridTemplateRows: "266px 266px",
    marginBottom: "100px",
    justifyContent: "bottom",
    gap: "24px",
  },
  gridItem: {
    borderRadius: "20px",
    img: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      borderRadius: "12px",
    },
  },
  spanTwoRows: {
    gridRow: "span 2",
  },
};
