export const cardStyles = {
  container: {
    width: "418px",
    minWidth: "390px",
    height: "388px",
    borderRadius: "10px",
    boxShadow: "0px 0px 4px rgba(159,164,189,0.3)",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    backgroundColor: "white",
    overflow: "visible",
    position: "relative",
  },
  imageWrapper: {
    width: "100%",
    height: "225px",
    borderRadius: "10px 10px 0 0",
    overflow: "hidden",
    "& img": {
      width: "100%",
      height: "100%",
      objectFit: "cover",
    },
  },
  cardContent: {
    marginX: "24px",
    marginBottom: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  textContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  title: {
    color: "#000000",
    fontFamily: "Poppins",
    fontSize: "20px",
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: "1",
    WebkitBoxOrient: "vertical",
  },
  description: {
    color: "#999999",
    fontFamily: "Poppins",
    fontSize: "16px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: "2",
    WebkitBoxOrient: "vertical",
  },
  destinationDetails: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "54px",
  },
  detailRow: {
    display: "flex",
    flexDirection: "row",
    gap: "8px",
    alignItems: "center",
  },
  text: {
    color: "#797C9A",
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: 400,
  },
  icon: {
    color: "#797C9A",
    padding: "3px",
    backgroundColor: "#F5F5F5",
    borderRadius: "50%",
  },
  myTours: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deleteIcon: {
    color: "#FF5C5C",
    cursor: "pointer",
    fontSize: "35px",
  },
  toursButton: {
    paddingX: "28px",
  },
  textContentWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: "18px",
    width: "100%",
    paddingTop: 0,
    backgroundColor: "white",
    borderRadius: "0 0 10px 10px",
    boxShadow:
      "4px 4px 4px -4px rgba(159,164,189,0.3), -4px 4px 4px -4px rgba(159,164,189,0.3)",
    transform: "translateY(30%)",
    zIndex: -1,
  },
};
